version: '3'

services:
  ui:
    image: chainlog-ui
    container_name: chainlog-ui
    ports:
      - "0.0.0.0:8080:80/tcp"
    volumes:
      - ./api:/usr/share/nginx/html/api
  logger:
    image: chainlog-logger
    container_name: chainlog-logger
    environment:
      INFURA_KEY: $INFURA_KEY
      PYTHONUNBUFFERED: 1
    volumes:
      - ./api:/usr/app/src/api
