replicaCount: 2
service:
  enabled: true
  name: chainlog-ui
  port: 8080
  type: ClusterIP
  containerPort: 8080
  tls:
    enabled: true
    issuerName: cloudflare
deployment:
  enabled: true
image:
  repository: ${ECR_REGISTRY}/chainlog-ui-prod
  pullPolicy: Always
  tag: prod
serviceAccount:
  create: false
ingress:
  enabled: true
  host: chainlog.makerdao.com
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
podAnnotations:
  reloader.stakater.com/auto: "true"
resources:
  limits:
    cpu: 0.3
    memory: 256Mi
  requests:
    cpu: 0.05
    memory: 64Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 60
env:
  CHECKSUM_CONTAINER_NAME:
    type: kv
    value: "localhost"
readinessProbe:
  tcpSocket:
    port: 8080
livenessProbe:
  tcpSocket:
    port: 8080
