replicaCount: 0
service:
  enabled: true
  name: chainlog-ui
  port: 8080
  type: ClusterIP
  containerPort: 8080
  tls:
    enabled: true
    issuerName: cloudflare
deployment:
  enabled: true
image:
  repository: ${ECR_REGISTRY}/chainlog-ui-staging
  pullPolicy: IfNotPresent
  tag: staging
serviceAccount:
  create: false
ingress:
  enabled: true
  host: chainlog-staging.makerdao.com
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
podAnnotations:
  reloader.stakater.com/auto: "true"
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 0
  maxReplicas: 0
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 60
env:
  CHECKSUM_CONTAINER_NAME:
    type: kv
    value: "localhost"
readinessProbe:
  tcpSocket:
    port: 8080
livenessProbe:
  tcpSocket:
    port: 8080
