on:
  push:
    branches:
      - dev

name: Deploy to AWS Staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging
    env:
      AWS_REGION: eu-central-1
      CLUSTER_NAME: chainlog-staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract commit hash
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        SHA_TAG: ${{ steps.vars.outputs.sha_short }}
        LATEST_TAG: latest
        ENVIRONMENT_TAG: staging
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Build Docker containers and
        # push them to ECR:
        # - chainlog-ui
        docker pull $ECR_REGISTRY/chainlog-ui-staging:$LATEST_TAG || true
        docker build -t chainlog-ui-staging \
                     -t $ECR_REGISTRY/chainlog-ui-staging:$SHA_TAG \
                     -t $ECR_REGISTRY/chainlog-ui-staging:$LATEST_TAG \
                     -t $ECR_REGISTRY/chainlog-ui-staging:$ENVIRONMENT_TAG \
                     -f Dockerfile.ui \
                     .
        docker push $ECR_REGISTRY/chainlog-ui-staging --all-tags
        # - chainlog-checksum
        docker pull $ECR_REGISTRY/chainlog-checksum-staging:$LATEST_TAG || true
        docker build -t chainlog-checksum-staging \
                     -t $ECR_REGISTRY/chainlog-checksum-staging:$SHA_TAG \
                     -t $ECR_REGISTRY/chainlog-checksum-staging:$LATEST_TAG \
                     -t $ECR_REGISTRY/chainlog-checksum-staging:$ENVIRONMENT_TAG \
                     -f Dockerfile.checksum \
                     .
        docker push $ECR_REGISTRY/chainlog-checksum-staging --all-tags
        # - chainlog-logger
        docker pull $ECR_REGISTRY/chainlog-logger-staging:$LATEST_TAG || true
        docker build -t chainlog-logger-staging \
                     -t $ECR_REGISTRY/chainlog-logger-staging:$SHA_TAG \
                     -t $ECR_REGISTRY/chainlog-logger-staging:$LATEST_TAG \
                     -t $ECR_REGISTRY/chainlog-logger-staging:$ENVIRONMENT_TAG \
                     -f Dockerfile.logger \
                     .
        docker push $ECR_REGISTRY/chainlog-logger-staging --all-tags

    - name: Update ECS service with latest Docker image
      id: service-update
      run: |
        aws ecs update-service --cluster $CLUSTER_NAME --service chainlog-ui-staging --force-new-deployment --region $AWS_REGION > /dev/null
        aws ecs update-service --cluster $CLUSTER_NAME --service chainlog-logger-staging --force-new-deployment --region $AWS_REGION > /dev/null

    - name: Wait for all services to become stable
      uses: oryanmoshe/ecs-wait-action@v1.3
      with:
        ecs-cluster: ${{ env.CLUSTER_NAME }}
        ecs-services: '["chainlog-ui-staging", "chainlog-logger-staging"]'
